version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

# We don't have any tests for this repo so there's only one job "deploy"
# "deploy" only runs on the master branch
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
